### ISSUE TITLE
The viewed jar is occupied and cannot be deleted

### ISSUE THREAD

**Issue by meiMingle** [Camork/file-expander-plugin#28] opened 2023-03-03 01:36 UTC
**Describe the bug**
When the jar package under the build folder is viewed through the File expander, the gradle clean command will fail because the jar package is in the occupied state.

### Environment & Stack Trace
- Plugin version:  2.1
- IDE version: 2022.3.2
- Operating System and version: Windows 10 
- Stack Trace:

**Comment by Camork** [comment] 2023-09-05 13:44
Sorry for the later, I can't reproduce this in v2023.2. Do you still get this problem?

**Comment by sticksabuser** [comment] 2023-09-08 19:23
I am having the same issue. I have a gradle task that copies a jar file (which happens to be the jython-installer jar) belonging to a custom gradle dependency configuration into a subfolder in the gradle build folder. That task is setup to delete that subfolder (and hence the jar) before re-creating it every time it is run. Without the plugin loaded, this works fine. However; when the plugin is loaded, not only does it fail to delete the subfolder, but also occasionally causes intellij to freeze. 

The versions of things involved:
- Java 11
- Gradle 8.2
- Intellij 2023.2.1 (Build #IC-232.9559.62)
- File Expander Plugin 2.2

**Comment by Camork** [comment] 2023-09-09 02:37
@sticksabuser can you give me a simple demo? I have tested if I open a jar inside Intellij, and delete it from Windows Explorer, but it's ok,  anything else I have left?

**Comment by sticksabuser** [comment] 2023-09-10 17:56
I'll try setting up something Monday.

**Comment by sticksabuser** [comment] 2023-09-12 17:44
I have created a public repo: https://github.com/sticksabuser/FileExpanderExample

Here are the steps to replicate (Apologies for being a little granular; I'm just trying to be explicit to make sure the issue can be repeated):

1. Clone.
2. Open as intellij project (I'm assuming you have the File Expander plugin installed and enabled).
3. Add gradle project.
4. Insure that gradle is using JDK 11 (in the gradle project tab, to right there's a gear, and at the bottom of the settings window that come up you can select the JDK). Also insure that the gradle wrapper is being used.
5. Run the task "copyJython" under the "build" set of tasks from the intellij gradle tab.
6. In the intellij project file browser tab, expand the "build/distribution" directory.
7. Insure that thar jar file is also expanded.
8. Try to run the "clean" task in the same manner that the "copyJython" task was run.

I hope this helps.

**Comment by meiMingle** [comment] 2023-09-13 06:43
> I have created a public repo: https://github.com/sticksabuser/FileExpanderExample
> 
> Here are the steps to replicate (Apologies for being a little granular; I'm just trying to be explicit to make sure the issue can be repeated):
> 
> 1. Clone.
> 2. Open as intellij project (I'm assuming you have the File Expander plugin installed and enabled).
> 3. Add gradle project.
> 4. Insure that gradle is using JDK 11 (in the gradle project tab, to right there's a gear, and at the bottom of the settings window that come up you can select the JDK). Also insure that the gradle wrapper is being used.
> 5. Run the task "copyJython" under the "build" set of tasks from the intellij gradle tab.
> 6. In the intellij project file browser tab, expand the "build/distribution" directory.
> 7. Insure that thar jar file is also expanded.
> 8. Try to run the "clean" task in the same manner that the "copyJython" task was run.
> 
> I hope this helps.

This is the same situation I encountered

**Comment by Camork** [comment] 2023-10-06 15:22
Resolved in v2.3, you may receive the marketplace update in about two days. Thanks for your feedback.

**Closed by Camork** 2023-10-06 15:22 UTC
Labels: bug
