### ISSUE TITLE
The archive file handle is still open after I am done looking at it

### ISSUE THREAD

**Issue by lilyevsky** [Camork/file-expander-plugin#12] opened 2020-08-27 15:48 UTC
This issue causes a big headache on Windows (Linux environment is fine).

As we all know, on Windows, unlike Linux, you cannot delete file or change it in any way if it is still open somewhere else.

In my build I generate a tarball, which I want to examine with this plugin. It comes very handy. However, after that I cannot rebuild, or remove the file. I cannot even remove it using IntelliJ itself. Closing only the current project window does not help. The only workaround is to close the whole IntelliJ app. Very annoying.

I understand that keeping the file open might be intentional, to optimize access to it, but maybe it is possible to provide some enhancements.
Here is a couple of ideas:
- Automatically release the handle when I collapse the archive view and close all views of its files.
- Provide option in the pop-up menu to close it; it should also collapse the view and close all related files views.

**Comment by Camork** [comment] 2020-08-28 02:00
Hey @lilyevsky , thanks for you attention for this plugin.  Can you post the Intellij and file-expander version?  I can't reproduce this bug in the latest version.  Addtionally, The resource management of archive files is under control of the Intellij platform and this plugin do nothing about file releasing. 

Here are some suggestions to check the problem:

1. update your Intellij(2020.2) or File-expander plugin version(v1.5) if it's out of date
2. check if another components hold the resources (intellij terminal for a example)
3. testing in a pure IDE environment

**Comment by lilyevsky** [comment] 2020-08-28 14:13
Hi @Camork 
I have the latest versions of both IntelliJ(2020.2) and plugin(1.5). In fact, I installed them just a couple of days back.
Here are detailed instructions of how to reproduce the problem.
First, make sure you are doing this on **Windows 10**.  Don't do it on Linux - Linux does not care about files being opened somewhere else, you can always delete them, so no problem there.

Open any of your projects in IntelliJ, and then create a new one in the second window. Let say, the new project is called MyTest.
In some other directory, create a dummy text file, say, test.txt, and then create a tarball containing that text file. Call it, say, mytest.tgz.

Copy mytest.tgz to the directory of MyTest project. Now you will see it in the IntelliJ MyTest window, thanks to the plugin.
Expand the tarball view, now you see text.txt file inside. Double-click on it, to **view the content** (this is the key part; if you never look at the content, you will not notice the issue).

Then close text.txt file view, collapse the mytest.tgz, and try to delete it. You can try from inside IntelliJ, or from command window - it wouldn't work, you will see error message.
Now close the MyTest project window, still the same problem.
Only if you exit IntelliJ **completely** (closing all other unrelated projects), then you can delete that tarball.

**Comment by Camork** [comment] 2020-08-31 01:46
The second window seems to be the problem, i will take a look recently.

**Comment by lilyevsky** [comment] 2020-08-31 04:28
@Camork 
Thanks Charles. You are right, I just tried zip file and there is no problem deleting it, even if I have a view of that text file open. Behaves just like in Linux, as expected.
This gives me hope that the fix is relatively easy.
Please let me know.

**Comment by lilyevsky** [comment] 2020-08-31 05:01
@Camork 
Just curious, is the problem in https://github.com/Camork/file-expander-plugin/blob/master/src/main/groovy/com/github/camork/filesystem/tar/TarFile.groovy#L48 ?
I see you close the  _fileInputStream, but you never close the wrapping TarArchiveInputStream, created in line 43.
Just a thought. Maybe it is closed somewhere else.

**Comment by Camork** [comment] 2020-09-03 13:03
> Just curious, is the problem in https://github.com/Camork/file-expander-plugin/blob/master/src/main/groovy/com/github/camork/filesystem/tar/TarFile.groovy#L48 ?
> I see you close the _fileInputStream, but you never close the wrapping TarArchiveInputStream, created in line 43.
> Just a thought. Maybe it is closed somewhere else.

@lilyevsky The wrapped inputstream will be closed inside the `TarArchiveInputStream`,  I committed the bug fix and push the version in Jetbrains marketplace and github release page. Thanks for catching that. Feel free to ask if you have another problems

**Closed by Camork** 2020-09-03 13:03 UTC
Labels: bug

**Comment by lilyevsky** [comment] 2020-09-04 13:30
Got the 1.6 update this morning, now it works fine. Thanks!
